/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as ExpoRouteImport } from './routes/_expo'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QualifyTokenRouteImport } from './routes/qualify.$token'
import { Route as HooksRunRemindersRouteImport } from './routes/hooks.run-reminders'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as ExpoRegisterRouteImport } from './routes/expo.register'
import { Route as ExpoEnquireExhibitorRouteImport } from './routes/expo.enquire-exhibitor'
import { Route as ApiEnquiriesRouteImport } from './routes/api.enquiries'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppMeetingsRouteImport } from './routes/_app.meetings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAutomationsRouteImport } from './routes/_app.automations'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppFormsIndexRouteImport } from './routes/_app.forms.index'
import { Route as AppContactsIndexRouteImport } from './routes/_app.contacts.index'
import { Route as AppApplicationsIndexRouteImport } from './routes/_app.applications.index'
import { Route as ApiSystemReadinessRouteImport } from './routes/api.system.readiness'
import { Route as ApiCampaignsSendRouteImport } from './routes/api.campaigns.send'
import { Route as ExpoExpoTemplatesRouteImport } from './routes/_expo.expo.templates'
import { Route as ExpoExpoReportsRouteImport } from './routes/_expo.expo.reports'
import { Route as ExpoExpoPackagesRouteImport } from './routes/_expo.expo.packages'
import { Route as ExpoExpoOnboardingRouteImport } from './routes/_expo.expo.onboarding'
import { Route as ExpoExpoMeetingsRouteImport } from './routes/_expo.expo.meetings'
import { Route as ExpoExpoInvoicesRouteImport } from './routes/_expo.expo.invoices'
import { Route as ExpoExpoDashboardRouteImport } from './routes/_expo.expo.dashboard'
import { Route as ExpoExpoAutomationsRouteImport } from './routes/_expo.expo.automations'
import { Route as ExpoExpoAdminRouteImport } from './routes/_expo.expo.admin'
import { Route as AppFormsNewRouteImport } from './routes/_app.forms.new'
import { Route as AppFormsIdRouteImport } from './routes/_app.forms.$id'
import { Route as AppContactsImportRouteImport } from './routes/_app.contacts.import'
import { Route as AppContactsIdRouteImport } from './routes/_app.contacts.$id'
import { Route as AppApplicationsIdRouteImport } from './routes/_app.applications.$id'
import { Route as ExpoExpoExhibitorsIndexRouteImport } from './routes/_expo.expo.exhibitors.index'
import { Route as ExpoExpoAttendeesIndexRouteImport } from './routes/_expo.expo.attendees.index'
import { Route as ApiAdminUsersInviteRouteImport } from './routes/api.admin.users.invite'
import { Route as ExpoExpoExhibitorsNewRouteImport } from './routes/_expo.expo.exhibitors.new'
import { Route as ExpoExpoExhibitorsIdRouteImport } from './routes/_expo.expo.exhibitors.$id'
import { Route as ExpoExpoAttendeesIdRouteImport } from './routes/_expo.expo.attendees.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpoRoute = ExpoRouteImport.update({
  id: '/_expo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QualifyTokenRoute = QualifyTokenRouteImport.update({
  id: '/qualify/$token',
  path: '/qualify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksRunRemindersRoute = HooksRunRemindersRouteImport.update({
  id: '/hooks/run-reminders',
  path: '/hooks/run-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpoRegisterRoute = ExpoRegisterRouteImport.update({
  id: '/expo/register',
  path: '/expo/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpoEnquireExhibitorRoute = ExpoEnquireExhibitorRouteImport.update({
  id: '/expo/enquire-exhibitor',
  path: '/expo/enquire-exhibitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnquiriesRoute = ApiEnquiriesRouteImport.update({
  id: '/api/enquiries',
  path: '/api/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsIndexRoute = AppFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsIndexRoute = AppApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AppRoute,
} as any)
const ApiSystemReadinessRoute = ApiSystemReadinessRouteImport.update({
  id: '/api/system/readiness',
  path: '/api/system/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsSendRoute = ApiCampaignsSendRouteImport.update({
  id: '/api/campaigns/send',
  path: '/api/campaigns/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpoExpoTemplatesRoute = ExpoExpoTemplatesRouteImport.update({
  id: '/expo/templates',
  path: '/expo/templates',
  getParentRoute: () => ExpoRoute,
} as any)
const ExpoExpoReportsRoute = ExpoExpoReportsRouteImport.update({
  id: '/expo/reports',
  path: '/expo/reports',
  getParentRoute: () => ExpoRoute,
} as any)
const ExpoExpoPackagesRoute = ExpoExpoPackagesRouteImport.update({
  id: '/expo/packages',
  path: '/expo/packages',
  getParentRoute: () => ExpoRoute,
} as any)
const ExpoExpoOnboardingRoute = ExpoExpoOnboardingRouteImport.update({
  id: '/expo/onboarding',
  path: '/expo/onboarding',
  getParentRoute: () => ExpoRoute,
} as any)
const ExpoExpoMeetingsRoute = ExpoExpoMeetingsRouteImport.update({
  id: '/expo/meetings',
  path: '/expo/meetings',
  getParentRoute: () => ExpoRoute,
} as any)
const ExpoExpoInvoicesRoute = ExpoExpoInvoicesRouteImport.update({
  id: '/expo/invoices',
  path: '/expo/invoices',
  getParentRoute: () => ExpoRoute,
} as any)
const ExpoExpoDashboardRoute = ExpoExpoDashboardRouteImport.update({
  id: '/expo/dashboard',
  path: '/expo/dashboard',
  getParentRoute: () => ExpoRoute,
} as any)
const ExpoExpoAutomationsRoute = ExpoExpoAutomationsRouteImport.update({
  id: '/expo/automations',
  path: '/expo/automations',
  getParentRoute: () => ExpoRoute,
} as any)
const ExpoExpoAdminRoute = ExpoExpoAdminRouteImport.update({
  id: '/expo/admin',
  path: '/expo/admin',
  getParentRoute: () => ExpoRoute,
} as any)
const AppFormsNewRoute = AppFormsNewRouteImport.update({
  id: '/forms/new',
  path: '/forms/new',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsIdRoute = AppFormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsImportRoute = AppContactsImportRouteImport.update({
  id: '/contacts/import',
  path: '/contacts/import',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIdRoute = AppContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsIdRoute = AppApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => AppRoute,
} as any)
const ExpoExpoExhibitorsIndexRoute = ExpoExpoExhibitorsIndexRouteImport.update({
  id: '/expo/exhibitors/',
  path: '/expo/exhibitors/',
  getParentRoute: () => ExpoRoute,
} as any)
const ExpoExpoAttendeesIndexRoute = ExpoExpoAttendeesIndexRouteImport.update({
  id: '/expo/attendees/',
  path: '/expo/attendees/',
  getParentRoute: () => ExpoRoute,
} as any)
const ApiAdminUsersInviteRoute = ApiAdminUsersInviteRouteImport.update({
  id: '/api/admin/users/invite',
  path: '/api/admin/users/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpoExpoExhibitorsNewRoute = ExpoExpoExhibitorsNewRouteImport.update({
  id: '/expo/exhibitors/new',
  path: '/expo/exhibitors/new',
  getParentRoute: () => ExpoRoute,
} as any)
const ExpoExpoExhibitorsIdRoute = ExpoExpoExhibitorsIdRouteImport.update({
  id: '/expo/exhibitors/$id',
  path: '/expo/exhibitors/$id',
  getParentRoute: () => ExpoRoute,
} as any)
const ExpoExpoAttendeesIdRoute = ExpoExpoAttendeesIdRouteImport.update({
  id: '/expo/attendees/$id',
  path: '/expo/attendees/$id',
  getParentRoute: () => ExpoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enquire': typeof EnquireRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/automations': typeof AppAutomationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/meetings': typeof AppMeetingsRoute
  '/payments': typeof AppPaymentsRoute
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRoute
  '/tasks': typeof AppTasksRoute
  '/templates': typeof AppTemplatesRoute
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/expo/enquire-exhibitor': typeof ExpoEnquireExhibitorRoute
  '/expo/register': typeof ExpoRegisterRoute
  '/f/$slug': typeof FSlugRoute
  '/hooks/run-reminders': typeof HooksRunRemindersRoute
  '/qualify/$token': typeof QualifyTokenRoute
  '/applications/$id': typeof AppApplicationsIdRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/contacts/import': typeof AppContactsImportRoute
  '/forms/$id': typeof AppFormsIdRoute
  '/forms/new': typeof AppFormsNewRoute
  '/expo/admin': typeof ExpoExpoAdminRoute
  '/expo/automations': typeof ExpoExpoAutomationsRoute
  '/expo/dashboard': typeof ExpoExpoDashboardRoute
  '/expo/invoices': typeof ExpoExpoInvoicesRoute
  '/expo/meetings': typeof ExpoExpoMeetingsRoute
  '/expo/onboarding': typeof ExpoExpoOnboardingRoute
  '/expo/packages': typeof ExpoExpoPackagesRoute
  '/expo/reports': typeof ExpoExpoReportsRoute
  '/expo/templates': typeof ExpoExpoTemplatesRoute
  '/api/campaigns/send': typeof ApiCampaignsSendRoute
  '/api/system/readiness': typeof ApiSystemReadinessRoute
  '/applications/': typeof AppApplicationsIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/forms/': typeof AppFormsIndexRoute
  '/expo/attendees/$id': typeof ExpoExpoAttendeesIdRoute
  '/expo/exhibitors/$id': typeof ExpoExpoExhibitorsIdRoute
  '/expo/exhibitors/new': typeof ExpoExpoExhibitorsNewRoute
  '/api/admin/users/invite': typeof ApiAdminUsersInviteRoute
  '/expo/attendees/': typeof ExpoExpoAttendeesIndexRoute
  '/expo/exhibitors/': typeof ExpoExpoExhibitorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enquire': typeof EnquireRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/automations': typeof AppAutomationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/meetings': typeof AppMeetingsRoute
  '/payments': typeof AppPaymentsRoute
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRoute
  '/tasks': typeof AppTasksRoute
  '/templates': typeof AppTemplatesRoute
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/expo/enquire-exhibitor': typeof ExpoEnquireExhibitorRoute
  '/expo/register': typeof ExpoRegisterRoute
  '/f/$slug': typeof FSlugRoute
  '/hooks/run-reminders': typeof HooksRunRemindersRoute
  '/qualify/$token': typeof QualifyTokenRoute
  '/applications/$id': typeof AppApplicationsIdRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/contacts/import': typeof AppContactsImportRoute
  '/forms/$id': typeof AppFormsIdRoute
  '/forms/new': typeof AppFormsNewRoute
  '/expo/admin': typeof ExpoExpoAdminRoute
  '/expo/automations': typeof ExpoExpoAutomationsRoute
  '/expo/dashboard': typeof ExpoExpoDashboardRoute
  '/expo/invoices': typeof ExpoExpoInvoicesRoute
  '/expo/meetings': typeof ExpoExpoMeetingsRoute
  '/expo/onboarding': typeof ExpoExpoOnboardingRoute
  '/expo/packages': typeof ExpoExpoPackagesRoute
  '/expo/reports': typeof ExpoExpoReportsRoute
  '/expo/templates': typeof ExpoExpoTemplatesRoute
  '/api/campaigns/send': typeof ApiCampaignsSendRoute
  '/api/system/readiness': typeof ApiSystemReadinessRoute
  '/applications': typeof AppApplicationsIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/forms': typeof AppFormsIndexRoute
  '/expo/attendees/$id': typeof ExpoExpoAttendeesIdRoute
  '/expo/exhibitors/$id': typeof ExpoExpoExhibitorsIdRoute
  '/expo/exhibitors/new': typeof ExpoExpoExhibitorsNewRoute
  '/api/admin/users/invite': typeof ApiAdminUsersInviteRoute
  '/expo/attendees': typeof ExpoExpoAttendeesIndexRoute
  '/expo/exhibitors': typeof ExpoExpoExhibitorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_expo': typeof ExpoRouteWithChildren
  '/enquire': typeof EnquireRoute
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/expo/enquire-exhibitor': typeof ExpoEnquireExhibitorRoute
  '/expo/register': typeof ExpoRegisterRoute
  '/f/$slug': typeof FSlugRoute
  '/hooks/run-reminders': typeof HooksRunRemindersRoute
  '/qualify/$token': typeof QualifyTokenRoute
  '/_app/applications/$id': typeof AppApplicationsIdRoute
  '/_app/contacts/$id': typeof AppContactsIdRoute
  '/_app/contacts/import': typeof AppContactsImportRoute
  '/_app/forms/$id': typeof AppFormsIdRoute
  '/_app/forms/new': typeof AppFormsNewRoute
  '/_expo/expo/admin': typeof ExpoExpoAdminRoute
  '/_expo/expo/automations': typeof ExpoExpoAutomationsRoute
  '/_expo/expo/dashboard': typeof ExpoExpoDashboardRoute
  '/_expo/expo/invoices': typeof ExpoExpoInvoicesRoute
  '/_expo/expo/meetings': typeof ExpoExpoMeetingsRoute
  '/_expo/expo/onboarding': typeof ExpoExpoOnboardingRoute
  '/_expo/expo/packages': typeof ExpoExpoPackagesRoute
  '/_expo/expo/reports': typeof ExpoExpoReportsRoute
  '/_expo/expo/templates': typeof ExpoExpoTemplatesRoute
  '/api/campaigns/send': typeof ApiCampaignsSendRoute
  '/api/system/readiness': typeof ApiSystemReadinessRoute
  '/_app/applications/': typeof AppApplicationsIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/forms/': typeof AppFormsIndexRoute
  '/_expo/expo/attendees/$id': typeof ExpoExpoAttendeesIdRoute
  '/_expo/expo/exhibitors/$id': typeof ExpoExpoExhibitorsIdRoute
  '/_expo/expo/exhibitors/new': typeof ExpoExpoExhibitorsNewRoute
  '/api/admin/users/invite': typeof ApiAdminUsersInviteRoute
  '/_expo/expo/attendees/': typeof ExpoExpoAttendeesIndexRoute
  '/_expo/expo/exhibitors/': typeof ExpoExpoExhibitorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/enquire'
    | '/login'
    | '/admin'
    | '/automations'
    | '/dashboard'
    | '/meetings'
    | '/payments'
    | '/pipeline'
    | '/reports'
    | '/tasks'
    | '/templates'
    | '/api/enquiries'
    | '/expo/enquire-exhibitor'
    | '/expo/register'
    | '/f/$slug'
    | '/hooks/run-reminders'
    | '/qualify/$token'
    | '/applications/$id'
    | '/contacts/$id'
    | '/contacts/import'
    | '/forms/$id'
    | '/forms/new'
    | '/expo/admin'
    | '/expo/automations'
    | '/expo/dashboard'
    | '/expo/invoices'
    | '/expo/meetings'
    | '/expo/onboarding'
    | '/expo/packages'
    | '/expo/reports'
    | '/expo/templates'
    | '/api/campaigns/send'
    | '/api/system/readiness'
    | '/applications/'
    | '/contacts/'
    | '/forms/'
    | '/expo/attendees/$id'
    | '/expo/exhibitors/$id'
    | '/expo/exhibitors/new'
    | '/api/admin/users/invite'
    | '/expo/attendees/'
    | '/expo/exhibitors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enquire'
    | '/login'
    | '/admin'
    | '/automations'
    | '/dashboard'
    | '/meetings'
    | '/payments'
    | '/pipeline'
    | '/reports'
    | '/tasks'
    | '/templates'
    | '/api/enquiries'
    | '/expo/enquire-exhibitor'
    | '/expo/register'
    | '/f/$slug'
    | '/hooks/run-reminders'
    | '/qualify/$token'
    | '/applications/$id'
    | '/contacts/$id'
    | '/contacts/import'
    | '/forms/$id'
    | '/forms/new'
    | '/expo/admin'
    | '/expo/automations'
    | '/expo/dashboard'
    | '/expo/invoices'
    | '/expo/meetings'
    | '/expo/onboarding'
    | '/expo/packages'
    | '/expo/reports'
    | '/expo/templates'
    | '/api/campaigns/send'
    | '/api/system/readiness'
    | '/applications'
    | '/contacts'
    | '/forms'
    | '/expo/attendees/$id'
    | '/expo/exhibitors/$id'
    | '/expo/exhibitors/new'
    | '/api/admin/users/invite'
    | '/expo/attendees'
    | '/expo/exhibitors'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_expo'
    | '/enquire'
    | '/login'
    | '/_app/admin'
    | '/_app/automations'
    | '/_app/dashboard'
    | '/_app/meetings'
    | '/_app/payments'
    | '/_app/pipeline'
    | '/_app/reports'
    | '/_app/tasks'
    | '/_app/templates'
    | '/api/enquiries'
    | '/expo/enquire-exhibitor'
    | '/expo/register'
    | '/f/$slug'
    | '/hooks/run-reminders'
    | '/qualify/$token'
    | '/_app/applications/$id'
    | '/_app/contacts/$id'
    | '/_app/contacts/import'
    | '/_app/forms/$id'
    | '/_app/forms/new'
    | '/_expo/expo/admin'
    | '/_expo/expo/automations'
    | '/_expo/expo/dashboard'
    | '/_expo/expo/invoices'
    | '/_expo/expo/meetings'
    | '/_expo/expo/onboarding'
    | '/_expo/expo/packages'
    | '/_expo/expo/reports'
    | '/_expo/expo/templates'
    | '/api/campaigns/send'
    | '/api/system/readiness'
    | '/_app/applications/'
    | '/_app/contacts/'
    | '/_app/forms/'
    | '/_expo/expo/attendees/$id'
    | '/_expo/expo/exhibitors/$id'
    | '/_expo/expo/exhibitors/new'
    | '/api/admin/users/invite'
    | '/_expo/expo/attendees/'
    | '/_expo/expo/exhibitors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ExpoRoute: typeof ExpoRouteWithChildren
  EnquireRoute: typeof EnquireRoute
  LoginRoute: typeof LoginRoute
  ApiEnquiriesRoute: typeof ApiEnquiriesRoute
  ExpoEnquireExhibitorRoute: typeof ExpoEnquireExhibitorRoute
  ExpoRegisterRoute: typeof ExpoRegisterRoute
  FSlugRoute: typeof FSlugRoute
  HooksRunRemindersRoute: typeof HooksRunRemindersRoute
  QualifyTokenRoute: typeof QualifyTokenRoute
  ApiCampaignsSendRoute: typeof ApiCampaignsSendRoute
  ApiSystemReadinessRoute: typeof ApiSystemReadinessRoute
  ApiAdminUsersInviteRoute: typeof ApiAdminUsersInviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_expo': {
      id: '/_expo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualify/$token': {
      id: '/qualify/$token'
      path: '/qualify/$token'
      fullPath: '/qualify/$token'
      preLoaderRoute: typeof QualifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/run-reminders': {
      id: '/hooks/run-reminders'
      path: '/hooks/run-reminders'
      fullPath: '/hooks/run-reminders'
      preLoaderRoute: typeof HooksRunRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expo/register': {
      id: '/expo/register'
      path: '/expo/register'
      fullPath: '/expo/register'
      preLoaderRoute: typeof ExpoRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expo/enquire-exhibitor': {
      id: '/expo/enquire-exhibitor'
      path: '/expo/enquire-exhibitor'
      fullPath: '/expo/enquire-exhibitor'
      preLoaderRoute: typeof ExpoEnquireExhibitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enquiries': {
      id: '/api/enquiries'
      path: '/api/enquiries'
      fullPath: '/api/enquiries'
      preLoaderRoute: typeof ApiEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms/': {
      id: '/_app/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AppFormsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications/': {
      id: '/_app/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AppApplicationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/system/readiness': {
      id: '/api/system/readiness'
      path: '/api/system/readiness'
      fullPath: '/api/system/readiness'
      preLoaderRoute: typeof ApiSystemReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns/send': {
      id: '/api/campaigns/send'
      path: '/api/campaigns/send'
      fullPath: '/api/campaigns/send'
      preLoaderRoute: typeof ApiCampaignsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_expo/expo/templates': {
      id: '/_expo/expo/templates'
      path: '/expo/templates'
      fullPath: '/expo/templates'
      preLoaderRoute: typeof ExpoExpoTemplatesRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/_expo/expo/reports': {
      id: '/_expo/expo/reports'
      path: '/expo/reports'
      fullPath: '/expo/reports'
      preLoaderRoute: typeof ExpoExpoReportsRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/_expo/expo/packages': {
      id: '/_expo/expo/packages'
      path: '/expo/packages'
      fullPath: '/expo/packages'
      preLoaderRoute: typeof ExpoExpoPackagesRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/_expo/expo/onboarding': {
      id: '/_expo/expo/onboarding'
      path: '/expo/onboarding'
      fullPath: '/expo/onboarding'
      preLoaderRoute: typeof ExpoExpoOnboardingRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/_expo/expo/meetings': {
      id: '/_expo/expo/meetings'
      path: '/expo/meetings'
      fullPath: '/expo/meetings'
      preLoaderRoute: typeof ExpoExpoMeetingsRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/_expo/expo/invoices': {
      id: '/_expo/expo/invoices'
      path: '/expo/invoices'
      fullPath: '/expo/invoices'
      preLoaderRoute: typeof ExpoExpoInvoicesRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/_expo/expo/dashboard': {
      id: '/_expo/expo/dashboard'
      path: '/expo/dashboard'
      fullPath: '/expo/dashboard'
      preLoaderRoute: typeof ExpoExpoDashboardRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/_expo/expo/automations': {
      id: '/_expo/expo/automations'
      path: '/expo/automations'
      fullPath: '/expo/automations'
      preLoaderRoute: typeof ExpoExpoAutomationsRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/_expo/expo/admin': {
      id: '/_expo/expo/admin'
      path: '/expo/admin'
      fullPath: '/expo/admin'
      preLoaderRoute: typeof ExpoExpoAdminRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/_app/forms/new': {
      id: '/_app/forms/new'
      path: '/forms/new'
      fullPath: '/forms/new'
      preLoaderRoute: typeof AppFormsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms/$id': {
      id: '/_app/forms/$id'
      path: '/forms/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof AppFormsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/import': {
      id: '/_app/contacts/import'
      path: '/contacts/import'
      fullPath: '/contacts/import'
      preLoaderRoute: typeof AppContactsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/$id': {
      id: '/_app/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AppContactsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications/$id': {
      id: '/_app/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AppApplicationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_expo/expo/exhibitors/': {
      id: '/_expo/expo/exhibitors/'
      path: '/expo/exhibitors'
      fullPath: '/expo/exhibitors/'
      preLoaderRoute: typeof ExpoExpoExhibitorsIndexRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/_expo/expo/attendees/': {
      id: '/_expo/expo/attendees/'
      path: '/expo/attendees'
      fullPath: '/expo/attendees/'
      preLoaderRoute: typeof ExpoExpoAttendeesIndexRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/api/admin/users/invite': {
      id: '/api/admin/users/invite'
      path: '/api/admin/users/invite'
      fullPath: '/api/admin/users/invite'
      preLoaderRoute: typeof ApiAdminUsersInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_expo/expo/exhibitors/new': {
      id: '/_expo/expo/exhibitors/new'
      path: '/expo/exhibitors/new'
      fullPath: '/expo/exhibitors/new'
      preLoaderRoute: typeof ExpoExpoExhibitorsNewRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/_expo/expo/exhibitors/$id': {
      id: '/_expo/expo/exhibitors/$id'
      path: '/expo/exhibitors/$id'
      fullPath: '/expo/exhibitors/$id'
      preLoaderRoute: typeof ExpoExpoExhibitorsIdRouteImport
      parentRoute: typeof ExpoRoute
    }
    '/_expo/expo/attendees/$id': {
      id: '/_expo/expo/attendees/$id'
      path: '/expo/attendees/$id'
      fullPath: '/expo/attendees/$id'
      preLoaderRoute: typeof ExpoExpoAttendeesIdRouteImport
      parentRoute: typeof ExpoRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppApplicationsIdRoute: typeof AppApplicationsIdRoute
  AppContactsIdRoute: typeof AppContactsIdRoute
  AppContactsImportRoute: typeof AppContactsImportRoute
  AppFormsIdRoute: typeof AppFormsIdRoute
  AppFormsNewRoute: typeof AppFormsNewRoute
  AppApplicationsIndexRoute: typeof AppApplicationsIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppFormsIndexRoute: typeof AppFormsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAutomationsRoute: AppAutomationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppReportsRoute: AppReportsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppApplicationsIdRoute: AppApplicationsIdRoute,
  AppContactsIdRoute: AppContactsIdRoute,
  AppContactsImportRoute: AppContactsImportRoute,
  AppFormsIdRoute: AppFormsIdRoute,
  AppFormsNewRoute: AppFormsNewRoute,
  AppApplicationsIndexRoute: AppApplicationsIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppFormsIndexRoute: AppFormsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ExpoRouteChildren {
  ExpoExpoAdminRoute: typeof ExpoExpoAdminRoute
  ExpoExpoAutomationsRoute: typeof ExpoExpoAutomationsRoute
  ExpoExpoDashboardRoute: typeof ExpoExpoDashboardRoute
  ExpoExpoInvoicesRoute: typeof ExpoExpoInvoicesRoute
  ExpoExpoMeetingsRoute: typeof ExpoExpoMeetingsRoute
  ExpoExpoOnboardingRoute: typeof ExpoExpoOnboardingRoute
  ExpoExpoPackagesRoute: typeof ExpoExpoPackagesRoute
  ExpoExpoReportsRoute: typeof ExpoExpoReportsRoute
  ExpoExpoTemplatesRoute: typeof ExpoExpoTemplatesRoute
  ExpoExpoAttendeesIdRoute: typeof ExpoExpoAttendeesIdRoute
  ExpoExpoExhibitorsIdRoute: typeof ExpoExpoExhibitorsIdRoute
  ExpoExpoExhibitorsNewRoute: typeof ExpoExpoExhibitorsNewRoute
  ExpoExpoAttendeesIndexRoute: typeof ExpoExpoAttendeesIndexRoute
  ExpoExpoExhibitorsIndexRoute: typeof ExpoExpoExhibitorsIndexRoute
}

const ExpoRouteChildren: ExpoRouteChildren = {
  ExpoExpoAdminRoute: ExpoExpoAdminRoute,
  ExpoExpoAutomationsRoute: ExpoExpoAutomationsRoute,
  ExpoExpoDashboardRoute: ExpoExpoDashboardRoute,
  ExpoExpoInvoicesRoute: ExpoExpoInvoicesRoute,
  ExpoExpoMeetingsRoute: ExpoExpoMeetingsRoute,
  ExpoExpoOnboardingRoute: ExpoExpoOnboardingRoute,
  ExpoExpoPackagesRoute: ExpoExpoPackagesRoute,
  ExpoExpoReportsRoute: ExpoExpoReportsRoute,
  ExpoExpoTemplatesRoute: ExpoExpoTemplatesRoute,
  ExpoExpoAttendeesIdRoute: ExpoExpoAttendeesIdRoute,
  ExpoExpoExhibitorsIdRoute: ExpoExpoExhibitorsIdRoute,
  ExpoExpoExhibitorsNewRoute: ExpoExpoExhibitorsNewRoute,
  ExpoExpoAttendeesIndexRoute: ExpoExpoAttendeesIndexRoute,
  ExpoExpoExhibitorsIndexRoute: ExpoExpoExhibitorsIndexRoute,
}

const ExpoRouteWithChildren = ExpoRoute._addFileChildren(ExpoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ExpoRoute: ExpoRouteWithChildren,
  EnquireRoute: EnquireRoute,
  LoginRoute: LoginRoute,
  ApiEnquiriesRoute: ApiEnquiriesRoute,
  ExpoEnquireExhibitorRoute: ExpoEnquireExhibitorRoute,
  ExpoRegisterRoute: ExpoRegisterRoute,
  FSlugRoute: FSlugRoute,
  HooksRunRemindersRoute: HooksRunRemindersRoute,
  QualifyTokenRoute: QualifyTokenRoute,
  ApiCampaignsSendRoute: ApiCampaignsSendRoute,
  ApiSystemReadinessRoute: ApiSystemReadinessRoute,
  ApiAdminUsersInviteRoute: ApiAdminUsersInviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
